# Generated by Django 4.2.30 on 2026-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="图片标题")),
                (
                    "image",
                    models.ImageField(
                        upload_to="knowledge/images/", verbose_name="图片文件"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="用逗号分隔，如：宿舍, 环境",
                        max_length=200,
                        verbose_name="标签",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "知识库图片",
                "db_table": "knowledge_image",
                "ordering": ["-created_at"],
            },
        ),
    ]
