# Generated by Django 4.2.30 on 2026-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_knowledgeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemprompt",
            name="role",
            field=models.TextField(blank=True, default="", verbose_name="角色设定"),
        ),
        migrations.AddField(
            model_name="systemprompt",
            name="skills",
            field=models.TextField(blank=True, default="", verbose_name="技能描述"),
        ),
        migrations.AlterField(
            model_name="systemprompt",
            name="content",
            field=models.TextField(
                blank=True, default="", verbose_name="完整提示词（自动生成）"
            ),
        ),
    ]
