# Generated by Django 4.2.30 on 2026-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_systemprompt_role_systemprompt_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                ("role", models.TextField(verbose_name="角色设定模板")),
                ("skills", models.TextField(verbose_name="技能描述模板")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "提示词模板",
                "db_table": "prompt_template",
                "ordering": ["-created_at"],
            },
        ),
    ]
